<div style="  background: linear-gradient(145deg, #0f172a, #1e293b);  border: 4px solid transparent;  border-radius: 14px;  padding: 18px 22px;  margin: 12px 0;  font-size: 26px;  font-weight: 600;  color: #f8fafc;  box-shadow: 0 6px 14px rgba(0,0,0,0.25);  background-clip: padding-box;  position: relative;">  <div style="    position: absolute;    inset: 0;    padding: 4px;    border-radius: 14px;    background: linear-gradient(90deg, #06b6d4, #3b82f6, #8b5cf6);    -webkit-mask:       linear-gradient(#fff 0 0) content-box,       linear-gradient(#fff 0 0);    -webkit-mask-composite: xor;    mask-composite: exclude;    pointer-events: none;  "></div>    <b>INTRODUCTION TO DEEP LEARNING WITH KERAS</b>    <br/>  <span style="color:#9ca3af; font-size: 18px; font-weight: 400;">(Binary, Multi-class, Multi-label Classification & Callbacks)</span></div>

## Table of Contents
1. [Binary Classification](#section-1)
2. [Multi-class Classification](#section-2)
3. [Multi-label Classification](#section-3)
4. [Keras Callbacks](#section-4)
5. [Conclusion](#section-5)

---

## <br><span style="  display: inline-block;  color: #fff;  background: linear-gradient(135deg, #a31616ff, #02b7ffff);  padding: 12px 20px;  border-radius: 12px;  font-size: 28px;  font-weight: 700;  box-shadow: 0 4px 12px rgba(0,0,0,0.2);  transition: transform 0.2s ease, box-shadow 0.2s ease;">  🧾 1. BINARY CLASSIFICATION</span><br>

### 1.1 When to use Binary Classification?

Binary classification is used when we need to distinguish between exactly two classes. A classic example is separating blue circles from red circles based on their coordinates.

**The Dataset**
The dataset typically consists of coordinates (features) and labels (targets). In this example, we have 2D coordinates and a binary label (0 or 1).

| coordinates | labels |
| :--- | :---: |
| [0.242, 0.038] | 1 |
| [0.044, -0.057] | 1 |
| [-0.787, -0.076] | 0 |

### 1.2 Visualizing Data with Pairplots

Before building a model, it is essential to visualize the data to understand the separability of the classes. We can use the `seaborn` library for this.

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.datasets import make_circles

# 1. Generate the "Circles" data
# factor=0.3 makes the inner circle much smaller than the outer one
X, y = make_circles(n_samples=1000, noise=0.1, factor=0.3, random_state=42)

# 2. Put into a DataFrame for Seaborn
df = pd.DataFrame(X, columns=['x1', 'x2'])
df['class'] = y

# 3. Visualize with Seaborn
plt.figure(figsize=(8, 8))
sns.scatterplot(data=df, x='x1', y='x2', hue='class', palette=['blue', 'red'], alpha=0.6)

plt.title("Separate Blue from Red circles")
plt.xlim(-1.5, 1.5)
plt.ylim(-1.5, 1.5)
plt.show()

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import make_circles

# Generate synthetic data (circles)
X, y = make_circles(n_samples=1000, noise=0.1, factor=0.2, random_state=42)

# Create a DataFrame
circles = pd.DataFrame({'x0': X[:, 0], 'x1': X[:, 1], 'target': y})

# Plot a pairplot
sns.pairplot(circles, hue="target")
plt.show()

### 1.3 Neural Network Architecture

To solve this problem, we use a neural network.
1.  **Input Layer:** Receives the coordinates.
2.  **Hidden Layer:** Processes features (e.g., 4 neurons, `tanh` activation).
3.  **Output Layer:** Produces the final prediction.

<div style="background: #e0f2fe; border-left: 16px solid #0284c7; padding: 14px 18px; border-radius: 8px; font-size: 18px; color: #075985;"> 💡 <b>Tip:</b> For binary classification, the output layer typically uses the <b>Sigmoid</b> activation function. It transforms the neuron output into a probability between 0 and 1. </div>

**The Sigmoid Function Logic:**
$$ \text{neuron output (3)} \rightarrow \text{sigmoid} \rightarrow \text{transformed output (0.95)} \rightarrow \text{rounded output (1)} $$



### 1.4 Building the Model in Keras

We will use the `Sequential` API from Keras to build the model layer by layer.

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Instantiate a sequential model
model = Sequential()

# Add input and hidden layer
# input_shape=(2,) corresponds to the x and y coordinates
model.add(Dense(4, input_shape=(2,), activation='tanh'))

# Add output layer, use sigmoid for binary classification
model.add(Dense(1, activation='sigmoid'))

# Summary of the model
model.summary()

### 1.5 Compiling, Training, and Predicting

In [ ]:
# Compile model
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

# Train model
# Using the 'circles' data 
# X contains coordinates, y contains labels
model.fit(X, y, epochs=20, verbose=1)

# Predict with trained model
preds = model.predict(X)

# Display first 5 predictions
print("First 5 predictions:\n", preds[:5])

### 1.6 Binary classification(`Breast Cancer` dataset)

In [ ]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from tensorflow import keras
from tensorflow.keras import layers

# Load sklearn dataset
data = load_breast_cancer()
X = data.data
y = data.target

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build Keras model
model = keras.Sequential([
    layers.Dense(16, activation="relu", input_shape=(X_train.shape[1],)),
    layers.Dense(8, activation="relu"),
    layers.Dense(1, activation="sigmoid")
])

# Compile model
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Train model
model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.1,
    verbose=2
)

In [ ]:
# Evaluate model
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

# Predict
predictions = model.predict(X_test[:5])
print("Probabilities:", predictions)

# Convert probabilities to class labels
class_preds = (predictions > 0.5).astype(int)
print("Predicted Classes:", class_preds)

### 1.7 Binary classification (`Banknotes` dataset)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers

# Load CSV
data = pd.read_csv("_datasets/banknotes.csv")  # replace with correct path
print(data.head())

# Assume the last column is the label
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build Keras model
model = keras.Sequential([
    layers.Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(8, activation='relu'),
    layers.Dense(1, activation='sigmoid')  # binary classification
])

# Compile model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train model
model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.1
)

# Evaluate
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

# Predict
preds = model.predict(X_test[:5])
print("Predicted Probabilities:", preds)
print("Predicted Classes:", (preds > 0.5).astype(int))

   variace  skewness  curtosis  entropy  class
0  3.62160    8.6661   -2.8073 -0.44699      0
1  4.54590    8.1674   -2.4586 -1.46210      0
2  3.86600   -2.6383    1.9242  0.10645      0
3  3.45660    9.5228   -4.0112 -3.59440      0
4  0.32924   -4.4552    4.5718 -0.98880      0
Epoch 1/20


e:\001_Github_Repo_all\applied-deep-learning-keras\.venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.4397 - loss: 0.7245 - val_accuracy: 0.4909 - val_loss: 0.6622
Epoch 2/20
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5299 - loss: 0.6573 - val_accuracy: 0.6727 - val_loss: 0.6106
Epoch 3/20
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6910 - loss: 0.5999 - val_accuracy: 0.7909 - val_loss: 0.5571
Epoch 4/20
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8369 - loss: 0.5386 - val_accuracy: 0.9000 - val_loss: 0.4951
Epoch 5/20
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9210 - loss: 0.4700 - val_accuracy: 0.9364 - val_loss: 0.4282
Epoch 6/20
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9514 - loss: 0.3956 - val_accuracy: 0.9636 - val_loss: 0.3574
Epoch 7/20
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9605 - loss: 0.3213 - val_accuracy: 0.9727 - val_loss: 0.2887
Epoch 8/20
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9645 - loss: 0.2525 - val_accuracy: 0.9727 - val_loss: 0.2276
Ep

---

## <br><span style="  display: inline-block;  color: #fff;  background: linear-gradient(135deg, #a31616ff, #02b7ffff);  padding: 12px 20px;  border-radius: 12px;  font-size: 28px;  font-weight: 700;  box-shadow: 0 4px 12px rgba(0,0,0,0.2);  transition: transform 0.2s ease, box-shadow 0.2s ease;">  🧾 2. MULTI-CLASS CLASSIFICATION</span><br>

### 2.1 The Concept

Multi-class classification involves distinguishing between **more than two** classes.
*   **Analogy:** Throwing darts where different regions correspond to different competitors (Steve, Susan, Michael, Kate).
*   **Dataset:** Features (`xCoord`, `yCoord`) and a categorical target (`competitor`).

**Example Dataset:**

| xCoord | yCoord | competitor |
| :--- | :--- | :--- |
| -0.037673 | 0.057402 | Steve |
| -0.331021 | -0.585035 | Susan |
| -0.123567 | 0.839730 | Susan |
| -0.086160 | 0.959787 | Michael |
| -0.902632 | 0.078753 | Michael |

### 2.2 Architecture for Multi-Class

The architecture changes slightly from binary classification:
1.  **Input/Hidden Layers:** Similar structure (e.g., 128 -> 64 -> 32 neurons).
2.  **Output Layer:** The number of neurons **must equal the number of classes**.
3.  **Activation:** We use **Softmax**.

**Softmax Output Example:**
Softmax ensures all output probabilities sum to 1.
- Michael: 0.6
- Susan: 0.1
- Kate: 0.2
- Steve: 0.1
- **Total:** 1.0

### 2.3 Building the Multi-Class Model

In [ ]:
# Define a multi-class model
mc_model = Sequential()

# Input layer and first hidden layer
mc_model.add(Dense(128, input_shape=(2,), activation='relu'))

# Additional hidden layers
mc_model.add(Dense(64, activation='relu'))
mc_model.add(Dense(32, activation='relu'))

# Output layer: 4 neurons (for 4 competitors), softmax activation
mc_model.add(Dense(4, activation='softmax'))

mc_model.summary()

### 2.4 Categorical Cross-Entropy

For multi-class problems, the loss function is `categorical_crossentropy`.

In [ ]:
model.compile(optimizer='adam', loss='categorical_crossentropy')

### 2.5 Preparing the Dataset (One-Hot Encoding)

Neural networks cannot understand text labels like "Steve" or "Susan". We must convert them into numbers.
1.  **Label Encoding:** Assign a number to each category (0, 1, 2, 3).
2.  **One-Hot Encoding:** Create a binary vector for each category.

**One-Hot Encoding Table:**

| Food Name | Categorical # | Calories | $\rightarrow$ | Apple | Chicken | Broccoli | Calories |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Apple | 1 | 95 | | 1 | 0 | 0 | 95 |
| Chicken | 2 | 231 | | 0 | 1 | 0 | 231 |
| Broccoli | 3 | 50 | | 0 | 0 | 1 | 50 |


In [ ]:
import pandas as pd
from tensorflow.keras.utils import to_categorical

# Load dataset
df = pd.read_csv('data.csv')

# Turn response variable into labeled codes
df.response = pd.Categorical(df.response)
df.response = df.response.cat.codes

# Turn response variable into one-hot response vector
y = to_categorical(df.response)

**Enhanced Runnable Code (with dummy data):**

In [ ]:
import pandas as pd
import numpy as np
from tensorflow.keras.utils import to_categorical

# Create dummy data
data = {
    'xCoord': np.random.rand(5),
    'yCoord': np.random.rand(5),
    'competitor': ['Steve', 'Susan', 'Susan', 'Michael', 'Michael']
}
df = pd.DataFrame(data)

print("Original Data:\n", df)

# Turn response variable into labeled codes
df['competitor_code'] = pd.Categorical(df['competitor']).codes

print("\nLabeled Codes:\n", df[['competitor', 'competitor_code']])

# Turn response variable into one-hot response vector
y_one_hot = to_categorical(df['competitor_code'])

print("\nOne-Hot Encoded Target:\n", y_one_hot)

### 2.6 Multi-Class classification (`Iris` dataset)

In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical

# Load sklearn dataset (3 classes)
data = load_iris()
X = data.data
y = data.target  # classes: 0, 1, 2 [setosa, versicolor, virginica]

# One-hot encode labels
y = to_categorical(y, num_classes=3)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build Keras model
model = keras.Sequential([
    layers.Dense(16, activation="relu", input_shape=(X_train.shape[1],)),
    layers.Dense(8, activation="relu"),
    layers.Dense(3, activation="softmax")  # 3 classes
])

# Compile model
model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

# Train model
model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=16,
    validation_split=0.1
)

Epoch 1/30


e:\001_Github_Repo_all\applied-deep-learning-keras\.venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.3056 - loss: 1.2022 - val_accuracy: 0.4167 - val_loss: 1.0788
Epoch 2/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3148 - loss: 1.1432 - val_accuracy: 0.4167 - val_loss: 1.0530
Epoch 3/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3333 - loss: 1.0882 - val_accuracy: 0.5000 - val_loss: 1.0284
Epoch 4/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3426 - loss: 1.0381 - val_accuracy: 0.5000 - val_loss: 1.0049
Epoch 5/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3611 - loss: 0.9897 - val_accuracy: 0.6667 - val_loss: 0.9801
Epoch 6/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4537 - loss: 0.9436 - val_accuracy: 0.6667 - val_loss: 0.9539
Epoch 7/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6111 - loss: 0.8983 - val_accuracy: 0.6667 - val_loss: 0.9286
Epoch 8/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7315 - loss: 0.8559 - val_accuracy: 0.6667 - val_loss: 0.9022
Epoch 9/30


In [23]:
# Evaluate model
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

# Predict
predictions = model.predict(X_test[:5])
print("Class probabilities:\n", predictions)

# Convert probabilities to class labels
class_preds = np.argmax(predictions, axis=1)
print("Predicted Classes:", class_preds)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8667 - loss: 0.3344
Test Accuracy: 0.8666666746139526
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
Class probabilities:
 [[0.11653354 0.41802305 0.46544343]
 [0.94040805 0.02456246 0.03502943]
 [0.00176584 0.07241853 0.92581564]
 [0.0907075  0.39806685 0.5112257 ]
 [0.05511475 0.35034245 0.5945428 ]]
Predicted Classes: [2 0 2 2 2]


---

## <br><span style="  display: inline-block;  color: #fff;  background: linear-gradient(135deg, #a31616ff, #02b7ffff);  padding: 12px 20px;  border-radius: 12px;  font-size: 28px;  font-weight: 700;  box-shadow: 0 4px 12px rgba(0,0,0,0.2);  transition: transform 0.2s ease, box-shadow 0.2s ease;">  🧾 3. MULTI-LABEL CLASSIFICATION</span><br>

### 3.1 The Concept

In multi-label classification, a single instance can belong to **multiple classes** simultaneously.
- **Example:** A TV show like *Game of Thrones* can be tagged as "Action", "Adventure", AND "Drama".
- **Irrigation Machine Example:** A sensor reading might indicate multiple parcels of land need water simultaneously.

### 3.2 Architecture Differences

- **Multi-Class:** Uses `softmax` (probabilities sum to 1, classes are mutually exclusive).
- **Multi-Label:** Uses `sigmoid` on the output layer. Each neuron outputs a probability between 0 and 1 independently of the others.

**Comparison:**

| Feature | Multi-Class | Multi-Label |
| :--- | :--- | :--- |
| **Example** | Sun OR Moon OR Cloud | Sun AND Cloud |
| **Labels** | [0 0 1] (Only one active) | [1 0 1] (Multiple active) |
| **Activation** | Softmax | Sigmoid |
| **Loss** | Categorical Cross-entropy | Binary Cross-entropy |

### 3.3 Building the Multi-Label Model

In [39]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Generate dummy multi-label data
# 100 samples, 10 features
X_train = np.random.random((100, 10))
# 100 samples, 3 possible labels (0 or 1 for each)
y_train = np.random.randint(2, size=(100, 3))

# Instantiate model
ml_model = Sequential()

# Add input and hidden layers
ml_model.add(Dense(16, input_shape=(10,), activation='relu'))

# Add an output layer for the 3 classes and sigmoid activation
# Sigmoid allows each output node to independently be close to 0 or 1
ml_model.add(Dense(3, activation='sigmoid'))

# Compile the model with binary crossentropy
ml_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
# validation_split creates a validation set automatically
history = ml_model.fit(X_train, y_train, epochs=10, validation_split=0.2, verbose=1)

Epoch 1/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 107ms/step - accuracy: 0.3125 - loss: 0.7249 - val_accuracy: 0.4000 - val_loss: 0.6870
Epoch 2/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3125 - loss: 0.7222 - val_accuracy: 0.4000 - val_loss: 0.6871
Epoch 3/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3125 - loss: 0.7189 - val_accuracy: 0.3500 - val_loss: 0.6881
Epoch 4/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3250 - loss: 0.7163 - val_accuracy: 0.3000 - val_loss: 0.6893
Epoch 5/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.3375 - loss: 0.7140 - val_accuracy: 0.3000 - val_loss: 0.6907
Epoch 6/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.3375 - loss: 0.7124 - val_accuracy: 0.3000 - val_loss: 0.6923
Epoch 7/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3375 - loss: 0.7104 - val_accuracy: 0.3000 - val_loss: 0.6940
Epoch 8/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3375 - loss: 0.7087 - val_accuracy: 0.3000 - val_loss: 0.6950

### 3.4 Multi-Label Model (`darts` dataset)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

# Load darts.csv
data = pd.read_csv("_datasets/darts.csv")

# Preprocess for Multi-Label (One-Hot Encoding)
data = pd.get_dummies(data, columns=['competitor'], prefix='', prefix_sep='')
data = data.astype(float)
print(data.head())

# Separate features and targets
# xCoord, yCoord are features
X = data[['xCoord', 'yCoord']].values
y = data.drop(['xCoord', 'yCoord'], axis=1).values

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build Keras model
model = keras.Sequential([
    layers.Dense(32, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(16, activation='relu'),
    layers.Dense(y.shape[1], activation='sigmoid')
])

# Compile model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train model
model.fit(
    X_train, y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

     xCoord    yCoord  Kate  Michael  Steve  Susan
0  0.196451 -0.520341   0.0      0.0    1.0    0.0
1  0.476027 -0.306763   0.0      0.0    0.0    1.0
2  0.003175 -0.980736   0.0      1.0    0.0    0.0
3  0.294078  0.267566   1.0      0.0    0.0    0.0
4 -0.051120  0.598946   0.0      0.0    1.0    0.0
Epoch 1/30


e:\001_Github_Repo_all\applied-deep-learning-keras\.venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


18/18 - 1s - 60ms/step - accuracy: 0.2361 - loss: 0.6906 - val_accuracy: 0.2031 - val_loss: 0.6813
Epoch 2/30
18/18 - 0s - 6ms/step - accuracy: 0.2378 - loss: 0.6639 - val_accuracy: 0.2031 - val_loss: 0.6608
Epoch 3/30
18/18 - 0s - 7ms/step - accuracy: 0.2378 - loss: 0.6406 - val_accuracy: 0.2031 - val_loss: 0.6395
Epoch 4/30
18/18 - 0s - 6ms/step - accuracy: 0.2500 - loss: 0.6177 - val_accuracy: 0.2031 - val_loss: 0.6191
Epoch 5/30
18/18 - 0s - 6ms/step - accuracy: 0.2483 - loss: 0.5964 - val_accuracy: 0.2031 - val_loss: 0.6000
Epoch 6/30
18/18 - 0s - 6ms/step - accuracy: 0.2483 - loss: 0.5778 - val_accuracy: 0.2031 - val_loss: 0.5844
Epoch 7/30
18/18 - 0s - 6ms/step - accuracy: 0.2500 - loss: 0.5645 - val_accuracy: 0.2031 - val_loss: 0.5743
Epoch 8/30
18/18 - 0s - 6ms/step - accuracy: 0.2760 - loss: 0.5565 - val_accuracy: 0.2344 - val_loss: 0.5686
Epoch 9/30
18/18 - 0s - 7ms/step - accuracy: 0.2882 - loss: 0.5516 - val_accuracy: 0.2500 - val_loss: 0.5634
Epoch 10/30
18/18 - 0s - 6ms/

In [38]:
# Evaluate
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

# Predict
preds = model.predict(X_test[:5])
label_preds = (preds > 0.5).astype(int)
print("Predicted Labels:\n", label_preds)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4625 - loss: 0.4819 
Test Accuracy: 0.4625000059604645
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
Predicted Labels:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### 3.5 Multi-Label Model (`irrigation_machine` dataset)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

# Load irrigation_machine.csv
data = pd.read_csv("_datasets/irrigation_machine.csv")
print(data.head())

# Assuming last N columns are multi-label targets
num_labels = 4  # change according to dataset
X = data.iloc[:, :-num_labels].values
y = data.iloc[:, -num_labels:].values

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build Keras model
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(y.shape[1], activation='sigmoid')  # multi-label output
])

# Compile model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train model
model.fit(
    X_train, y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

   Unnamed: 0  sensor_0  sensor_1  sensor_2  sensor_3  sensor_4  sensor_5  \
0           0       1.0       2.0       1.0       7.0       0.0       1.0   
1           1       5.0       1.0       3.0       5.0       2.0       2.0   
2           2       3.0       1.0       4.0       3.0       4.0       0.0   
3           3       2.0       2.0       4.0       3.0       5.0       0.0   
4           4       4.0       3.0       3.0       2.0       5.0       1.0   

   sensor_6  sensor_7  sensor_8  ...  sensor_13  sensor_14  sensor_15  \
0       1.0       4.0       0.0  ...        8.0        1.0        0.0   
1       1.0       2.0       3.0  ...        4.0        5.0        5.0   
2       1.0       6.0       0.0  ...        3.0        3.0        1.0   
3       3.0       2.0       2.0  ...        4.0        1.0        1.0   
4       3.0       1.0       1.0  ...        1.0        3.0        2.0   

   sensor_16  sensor_17  sensor_18  sensor_19  parcel_0  parcel_1  parcel_2  
0        2.0        

e:\001_Github_Repo_all\applied-deep-learning-keras\.venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


45/45 - 1s - 25ms/step - accuracy: 0.7354 - loss: 0.1074 - val_accuracy: 0.9000 - val_loss: -6.7699e-01
Epoch 2/30
45/45 - 0s - 3ms/step - accuracy: 0.8076 - loss: -1.0505e+00 - val_accuracy: 0.9000 - val_loss: -2.7618e+00
Epoch 3/30
45/45 - 0s - 4ms/step - accuracy: 0.8076 - loss: -3.5776e+00 - val_accuracy: 0.9000 - val_loss: -7.8909e+00
Epoch 4/30
45/45 - 0s - 3ms/step - accuracy: 0.8076 - loss: -9.4583e+00 - val_accuracy: 0.9000 - val_loss: -1.8770e+01
Epoch 5/30
45/45 - 0s - 3ms/step - accuracy: 0.8076 - loss: -2.0893e+01 - val_accuracy: 0.9000 - val_loss: -3.9137e+01
Epoch 6/30
45/45 - 0s - 3ms/step - accuracy: 0.8076 - loss: -4.1590e+01 - val_accuracy: 0.9000 - val_loss: -7.1809e+01
Epoch 7/30
45/45 - 0s - 3ms/step - accuracy: 0.8076 - loss: -7.4947e+01 - val_accuracy: 0.9000 - val_loss: -1.2490e+02
Epoch 8/30
45/45 - 0s - 3ms/step - accuracy: 0.8076 - loss: -1.2491e+02 - val_accuracy: 0.9000 - val_loss: -2.0013e+02
Epoch 9/30
45/45 - 0s - 3ms/step - accuracy: 0.8076 - loss: -1.

In [31]:
# Evaluate
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

# Predict
preds = model.predict(X_test[:5])
label_preds = (preds > 0.5).astype(int)
print("Predicted Labels:\n", label_preds)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4437 - loss: 0.4471 
Test Accuracy: 0.4437499940395355
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
Predicted Labels:
 [[0 0 1 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 1 0]]


---

## <br><span style="  display: inline-block;  color: #fff;  background: linear-gradient(135deg, #a31616ff, #02b7ffff);  padding: 12px 20px;  border-radius: 12px;  font-size: 28px;  font-weight: 700;  box-shadow: 0 4px 12px rgba(0,0,0,0.2);  transition: transform 0.2s ease, box-shadow 0.2s ease;">  🧾 4. KERAS CALLBACKS</span><br>

### 4.1 What is a Callback?

A callback is a set of functions to be applied at given stages of the training procedure. You can use callbacks to get a view on internal states and statistics of the model during training.

### 4.2 The History Callback

The `fit()` method returns a `History` object. This object has a member `history`, which is a dictionary containing data about everything that happened during training.


**Plotting History:**
We can visualize the training progress using Matplotlib.


```python
import matplotlib.pyplot as plt

# Plot train vs test accuracy per epoch
plt.figure()

# Use the history metrics
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

# Make it pretty
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'])
plt.show()
```

### 4.3 Early Stopping

Early stopping is a technique to prevent overfitting. It stops training when a monitored metric (like validation loss) has stopped improving.

<div style="background: #e0f2fe; border-left: 16px solid #0284c7; padding: 14px 18px; border-radius: 8px; font-size: 18px; color: #075985;"> 💡 <b>Tip:</b> The `patience` parameter determines how many epochs to wait after the metric stops improving before actually stopping the training. </div>


```python
# Import early stopping from keras callbacks
from tensorflow.keras.callbacks import EarlyStopping

# Instantiate an early stopping callback
early_stopping = EarlyStopping(monitor='val_loss', patience=5)

# Train your model with the callback
model.fit(X_train, y_train, epochs=100,
          validation_data=(X_test, y_test),
          callbacks=[early_stopping]
          )
```

### 4.4 Model Checkpoint

- `ModelCheckpoint` saves the model at some interval, so the model can be loaded later to continue training from the state saved. 

- `save_best_only=True` ensures you only save the model when it performs better than previous epochs.

```python
# Import model checkpoint from keras callbacks
from tensorflow.keras.callbacks import ModelCheckpoint

# Instantiate a model checkpoint callback
model_save = ModelCheckpoint('best_model.hdf5', save_best_only=True)

# Train your model with the callback
model.fit(X_train, y_train, epochs=100,
          validation_data=(X_test, y_test),
          callbacks=[model_save])
```

---

```python
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# 1. Define Early Stopping
early_stop = EarlyStopping(monitor='val_loss', patience=3, verbose=1)

# 2. Define Model Checkpoint
# We use a temporary filename for the example
checkpoint = ModelCheckpoint('best_run_model.keras', save_best_only=True, verbose=1)

# 3. Train with both callbacks
# Using the multi-label model and data from the previous section
history_cb = ml_model.fit(
    X_train, y_train, 
    epochs=50, 
    validation_split=0.2, 
    callbacks=[early_stop, checkpoint],
    verbose=0 # Silencing output for brevity in notebook
)

print("Training finished.")
print(f"Stopped at epoch: {len(history_cb.history['loss'])}")
```
```

### 4.5 Multi-Class classification (`Iris` dataset) ~ **Callbacks** -> `EarlyStopping`, `ModelCheckpoint` and `ReduceLROnPlateau`

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers, regularizers
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau # import callbacks

# -----------------------------
# Load Digits dataset
# -----------------------------
X = np.load("_datasets/Digits/digits_pixels.npy")  # shape: (n_samples, n_features)
y = np.load("_datasets/Digits/digits_target.npy")  # shape: (n_samples,)

num_classes = len(np.unique(y))
y = to_categorical(y, num_classes=num_classes)

# -----------------------------
# Train-test split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# -----------------------------
# Feature scaling
# -----------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# -----------------------------
# Build Keras model
# -----------------------------
model = keras.Sequential([
    keras.Input(shape=(X_train.shape[1],)),  # recommended Input layer
    layers.Dense(64, activation="relu", kernel_regularizer=regularizers.l2(0.001)),
    layers.Dropout(0.2),
    layers.Dense(32, activation="relu", kernel_regularizer=regularizers.l2(0.001)),
    layers.Dropout(0.2),
    layers.Dense(num_classes, activation="softmax")
])

# -----------------------------
# Compile model
# -----------------------------
model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

# -----------------------------
# Callbacks
# -----------------------------
callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True), # stop training when validation loss stops improving
    ModelCheckpoint('best_digits_model.keras', save_best_only=True),          # save the best model
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3)             # reduce learning rate when validation loss stops improving
]

# -----------------------------
# Train model
# -----------------------------
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.1,
    callbacks=callbacks,
    verbose=1
)

# -----------------------------
# Evaluate model
# -----------------------------
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}")

# -----------------------------
# Predict on first 10 test samples
# -----------------------------
predictions = model.predict(X_test[:10])
class_preds = np.argmax(predictions, axis=1)
true_classes = np.argmax(y_test[:10], axis=1)

print("Predicted Classes:", class_preds)
print("True Classes     :", true_classes)

# -----------------------------
# Visualize predictions
# -----------------------------
plt.figure(figsize=(12, 4))
for i in range(10):
    plt.subplot(2, 5, i+1)
    plt.imshow(X_test[i].reshape(8, 8), cmap='gray')  # adjust shape if necessary
    plt.title(f"P: {class_preds[i]}, T: {true_classes[i]}")
    plt.axis('off')
plt.tight_layout()
plt.show()

---

## <br><span style="  display: inline-block;  color: #fff;  background: linear-gradient(135deg, #a31616ff, #02b7ffff);  padding: 12px 20px;  border-radius: 12px;  font-size: 28px;  font-weight: 700;  box-shadow: 0 4px 12px rgba(0,0,0,0.2);  transition: transform 0.2s ease, box-shadow 0.2s ease;">  🧾 5. CONCLUSION</span><br>



### **1. Binary Classification**

* **Use case:** 2 classes (e.g., spam vs. not spam)
* **Model output:**  = `1 neuron`
* **Activation:** `sigmoid`
* **Loss function:** `binary_crossentropy`
* **Metrics:** `accuracy`, `AUC`

```python
model = Sequential([
    Dense(16, activation='relu', input_shape=(input_dim,)),
    Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
```

---

### **2. Multi-Class Classification**

* **Use case:** >2 mutually exclusive classes (e.g., digit recognition 0–9)
* **Model output:** `Number of neurons = number of classes`
* **Activation:** `softmax`
* **Loss function:** `categorical_crossentropy`
* **Data prep:** One-hot encode labels (`to_categorical`)
* **Metrics:** `accuracy`

```python
from tensorflow.keras.utils import to_categorical
y_train_encoded = to_categorical(y_train, num_classes)
```

---

### **3. Multi-Label Classification**

* **Use case:** Items can belong to multiple classes (e.g., image tagging)
* **Model output:** Number of neurons = number of possible labels
* **Activation:** `sigmoid` (per neuron)
* **Loss function:** `binary_crossentropy`
* **Metrics:** `accuracy`, `AUC`

---

### **4. Callbacks**

* **`History`** – Logs training & validation metrics for plotting
* **`EarlyStopping`** – Stop training when validation loss stops improving
* **`ModelCheckpoint`** – Save the best model during training
* **`ReduceLROnPlateau`** – Reduce learning rate when metrics plateau

```python
callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),
    ModelCheckpoint('best_model.h5', save_best_only=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3)
]
```

---

### **5. Common Optimizers**

| Optimizer | Key Notes                                      |
| --------- | ---------------------------------------------- |
| SGD       | Basic, allows momentum and learning rate decay |
| Adam      | Adaptive learning rates, widely used           |
| RMSprop   | Good for RNNs or online learning               |
| Adagrad   | Good for sparse data                           |

---

### **6. Common Activation Functions**

| Activation | Use Case                                  |
| ---------- | ----------------------------------------- |
| ReLU       | Hidden layers, most common                |
| Sigmoid    | Binary classification output              |
| Softmax    | Multi-class output                        |
| Tanh       | Hidden layers, sometimes better than ReLU |

---

### **7. Metrics Overview**

* **Accuracy** – Correct predictions / total
* **Precision / Recall / F1-score** – Important for imbalanced datasets
* **AUC-ROC** – Probability ranking quality

---

### **8. Data Preprocessing Tips**

* **Normalization:** `x = (x - mean) / std` or `x = x / 255` for images
* **One-Hot Encoding:** For multi-class classification
* **Train/Validation Split:** `train_test_split` or `validation_split` in `model.fit`

---

### **9. Training Tips**

* Start simple → few layers, small neurons
* Use dropout to prevent overfitting
* Monitor training vs. validation loss for overfitting signs
* Batch size: 32–128 (common), tune for your dataset
* Epochs: Start small (10–50), use EarlyStopping

---

### **10. Next Steps / Experiments**

* Try datasets: `MNIST`, `CIFAR-10`, `IMDB  `, `Titanic`
* Experiment with different hidden layers & neurons
* Try different optimizers and learning rates
* Apply regularization (`Dropout`, `L2`)
* Explore pretrained models (`Transfer Learning`)